// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFF0zWh5JAUQaAjD85kVVMCVyNLD_qbQc',
    appId: '1:409513813064:web:df11fa7f14e639a7ea647d',
    messagingSenderId: '409513813064',
    projectId: 'dojochallenges',
    authDomain: 'dojochallenges.firebaseapp.com',
    storageBucket: 'dojochallenges.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEzMdRF5tQdchgYq9lCfLh6C9TG-qeF0w',
    appId: '1:409513813064:android:18c911787efc80b3ea647d',
    messagingSenderId: '409513813064',
    projectId: 'dojochallenges',
    storageBucket: 'dojochallenges.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC56s34pdzaLTKS0xFTupJcT1XrybJBs00',
    appId: '1:409513813064:ios:33eb4564f4669567ea647d',
    messagingSenderId: '409513813064',
    projectId: 'dojochallenges',
    storageBucket: 'dojochallenges.firebasestorage.app',
    iosBundleId: 'com.example.dojoChallenges',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC56s34pdzaLTKS0xFTupJcT1XrybJBs00',
    appId: '1:409513813064:ios:33eb4564f4669567ea647d',
    messagingSenderId: '409513813064',
    projectId: 'dojochallenges',
    storageBucket: 'dojochallenges.firebasestorage.app',
    iosBundleId: 'com.example.dojoChallenges',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFF0zWh5JAUQaAjD85kVVMCVyNLD_qbQc',
    appId: '1:409513813064:web:436f96cb7d08a6a0ea647d',
    messagingSenderId: '409513813064',
    projectId: 'dojochallenges',
    authDomain: 'dojochallenges.firebaseapp.com',
    storageBucket: 'dojochallenges.firebasestorage.app',
  );
}
